### ISSUE TITLE
configOverrides error, cannot find module "expressServer"

### ISSUE THREAD

**Issue by coreyferguson** [coreyferguson/karma-express-server#2]
This happens to a consumer. Not sure why yet. It works on release 1.0.0 but stops working on 1.0.2.
